name: Deploy GitHub Pages (DEV)

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-dev"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact (DEV)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages/dev

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages (DEV)
        id: deployment
        uses: actions/deploy-pages@v4
